chavyleung/scripts

10010/10010.cookie.js, 10010/10010.js
=> Fix 修复Quantumult X 下脚本执行超时的问题

10000/10000.js, 10000/README.md
测试 。查看与sign加密算法不一致，需要抓包body
仅支持显示被抓包的号码数据。显示到第一个手机号位置
=> 更新[中国电信] 增加金币总数测试显示

jd/JD_BaiTiao.js
=> 新增[京东白条]：每日+周五领白条券

suning/suning.js
=> 更新[苏宁易购] 修正链接

wanda/wanda.js
=> 更新[万达电影]，更改为9月signcode

10010/10010.js, csdn/csdn.js, everphoto/everphoto.js, mcdd/mcdd.js, rrtv/rrtv.js, suning/suning.js, videoqq/videoqq.js
QX 432版本，如果提前 $done, 后续代码将不执行。
.catch查阅文档只有一个参数。旧脚本写了两个参数。
=> 更新: 修复脚本提前 $done 问题

10086/10086.fee.cookie.js, wanda/wanda.cookie.js
=> 修复 loon 抓包配置的注释问题：万达，10086

wanda/wanda.js
=> 更新[万达电影]: 2021 年 2 月 signcode

box/chavy.boxjs.html, box/chavy.boxjs.js, box/release/box.release.json, box/release/box.release.tf.json, chavy.box.js
尽可能降低这个设置对小白用户的影响将文本框放在了偏好设置最下面，悬浮按钮效果如图。
添加Quantumult X重写方式的BoxJs有一个无法删除备份的bug，可能是Quantumult X层面的bug无法定位，请求失败，不会出现在Quantumult X脚本记录与网络活动日志中，应该需要反馈给作者看是什么问题。
使用HTTP Backend则不会出现这个问题，Surge使用一样正常。
添加baseURL参数和访问127.0.0.1:9999看起来不够“优雅”，在切换Surge与Quantumult X时访问方式不够统一，添加了这一项设置。
=> 更新[BoxJs]: 偏好设置内可以设定Quantumult X HTTP Backend，页面底部预留悬浮按钮空间

box/chavy.boxjs.html, box/chavy.boxjs.js, box/release/box.release.json, box/release/box.release.tf.json, chavy.box.js
=> fix setWallpaper

wanda/wanda.js
=> 更新[万达电影]: 2021 年 4 月 signcode

wanda/wanda.js
更新[万达电影]: 2021 年 5 月 signcode
晚了一点..
=> 更新[万达电影]: 2021 年 5 月 signcode

wanda/wanda.js
=> 更新[万达电影]: 2021 年 6 月 signcode

wanda/wanda.js
=> 2022年1月份最新signCode

sfexpress/sfexpress.js
=> 42 Patch 更新[顺丰速运]

box/rewrite/boxjs.rewrite.loon.plugin, box/rewrite/boxjs.rewrite.loon.tf.plugin, box/rewrite/boxjs.rewrite.quanx.conf, box/rewrite/boxjs.rewrite.quanx.tf.conf, box/rewrite/boxjs.rewrite.stash.stoverride, box/rewrite/boxjs.rewrite.stash.tf.stoverride, box/rewrite/boxjs.rewrite.surge.sgmodule, box/rewrite/boxjs.rewrite.surge.tf.sgmodule
解决一下小白误入www.boxjs.com或者ww7.boxjs.com的问题
另：loon的plugin无须%INSERT%，默认使用%APPEND%行为
=> fix(boxjs): regex for *.boxjs.com/net

box/chavy.boxjs.js, box/release/box.release.json, box/release/box.release.tf.json, chavy.box.js
=> fix(BoxJs): done*() at ShadowRocket and Stash

zsfc/README.md, zsfc/zsfc.js
更新[掌上飞车]:修复月底某些宝箱领取失败的bug，修改README.md教程
=> 更新[掌上飞车]:修复月底某些宝箱领取失败的bug，修改README.md教程

box/chavy.boxjs.js, box/release/box.release.json, box/release/box.release.tf.json, chavy.box.js
=> 临时优化会话 JSON 过大，导致所有会话操作失效

v2ex/quanx/v2ex.cookie.js, v2ex/v2ex.cookie.js
=> fix(v2ex): 修复获取不到 Cookie 的问题

Env.js, box/chavy.boxjs.html, box/chavy.boxjs.js, box/release/box.release.json, box/release/box.release.tf.json, chavy.box.js
通过header传递boxjsAppId，env中再根据boxjsAppId获取该app的当前会话id，实现更新会话存储
=> fix(boxjs): 保存设置时更新boxjs会话存储

zsfc/README.md, zsfc/zsfc.js
上一个pr在配置文件中的正则表达式忘记修改了，这一版本更正这个表达式
=> 更新[掌上飞车]每日签到脚本及说明

zsfc/zsfc.treasure.js
=> 修复[掌飞寻宝]BUG

zsfc/zsfc.treasure.js
=> 修改错误的正则表达式，修正错误的逻辑判断

box/chavy.boxjs.html
[items 为字符串时，可读取持久化数据作为 items](https://github.com/chavyleung/scripts/pull/483)
=>  feat(modalSelects): select items

zsfc/zsfc.js
5月船新版本 旧版本无法进行签到操作 暂时更新一版看看 可能会周更也可能会月更 稳定后再优化一下领取奖励的一些逻辑
=> 更新[掌上飞车]适配5月新版

ithome/ithome.cookie.js, ithome/ithome.js
经过抓包，优化了新版cookie的正则获取，以及平替新的API接口，Loon测试已通过
=> fix(ithome): 匹配新版cookie获取以及域名替换
